"""add balancer tables

Revision ID: 0b25e7fbb760
Revises: 593d49338f2d
Create Date: 2025-12-26 11:01:02.413731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b25e7fbb760'
down_revision: Union[str, None] = '593d49338f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balancer_policy_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('supplier', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('segment_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('segment_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_porog_by_band', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('reason_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('is_applied', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("mode IN ('TEST','LIVE')", name='ck_balancer_policy_log_mode'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balancer_policy_log_city'), 'balancer_policy_log', ['city'], unique=False)
    op.create_index(op.f('ix_balancer_policy_log_hash'), 'balancer_policy_log', ['hash'], unique=False)
    op.create_index(op.f('ix_balancer_policy_log_segment_id'), 'balancer_policy_log', ['segment_id'], unique=False)
    op.create_index(op.f('ix_balancer_policy_log_supplier'), 'balancer_policy_log', ['supplier'], unique=False)
    op.create_index('ix_balancer_policy_scope', 'balancer_policy_log', ['city', 'supplier', 'segment_id', 'segment_start'], unique=False)
    op.create_table('balancer_order_facts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('policy_log_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('supplier', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('segment_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('segment_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('band_id', sa.String(), nullable=False),
    sa.Column('band_min_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('band_max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('porog_used', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('min_porog', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('min_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('excess_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_in_scope', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("mode IN ('TEST','LIVE')", name='ck_balancer_order_facts_mode'),
    sa.CheckConstraint('cost >= 0', name='ck_balancer_order_facts_cost_nonneg'),
    sa.CheckConstraint('sale_price >= 0', name='ck_balancer_order_facts_sale_nonneg'),
    sa.ForeignKeyConstraint(['policy_log_id'], ['balancer_policy_log.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_log_id', 'order_id', name='uq_balancer_order_facts_policy_order')
    )
    op.create_index(op.f('ix_balancer_order_facts_band_id'), 'balancer_order_facts', ['band_id'], unique=False)
    op.create_index(op.f('ix_balancer_order_facts_city'), 'balancer_order_facts', ['city'], unique=False)
    op.create_index(op.f('ix_balancer_order_facts_order_id'), 'balancer_order_facts', ['order_id'], unique=False)
    op.create_index(op.f('ix_balancer_order_facts_policy_log_id'), 'balancer_order_facts', ['policy_log_id'], unique=False)
    op.create_index(op.f('ix_balancer_order_facts_profile_name'), 'balancer_order_facts', ['profile_name'], unique=False)
    op.create_index('ix_balancer_order_facts_scope', 'balancer_order_facts', ['city', 'supplier', 'segment_id', 'band_id', 'segment_start'], unique=False)
    op.create_index(op.f('ix_balancer_order_facts_segment_id'), 'balancer_order_facts', ['segment_id'], unique=False)
    op.create_index(op.f('ix_balancer_order_facts_supplier'), 'balancer_order_facts', ['supplier'], unique=False)
    op.create_table('balancer_segment_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('policy_log_id', sa.BigInteger(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('supplier', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('segment_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('segment_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('band_id', sa.String(), nullable=False),
    sa.Column('band_min_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('band_max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('porog_used', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('min_porog', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('orders_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sale_sum', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_sum', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('profit_sum', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('min_profit_sum', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('excess_profit_sum', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('excess_profit_per_order', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('day_date', sa.Date(), nullable=False),
    sa.Column('day_total_orders', sa.Integer(), nullable=True),
    sa.Column('segment_share', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('orders_sample_ok', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("mode IN ('TEST','LIVE')", name='ck_balancer_segment_stats_mode'),
    sa.CheckConstraint('cost_sum >= 0', name='ck_balancer_seg_cost_nonneg'),
    sa.CheckConstraint('orders_count >= 0', name='ck_balancer_seg_orders_nonneg'),
    sa.CheckConstraint('porog_used >= min_porog', name='ck_balancer_seg_porog_ge_min'),
    sa.CheckConstraint('sale_sum >= 0', name='ck_balancer_seg_sale_nonneg'),
    sa.ForeignKeyConstraint(['policy_log_id'], ['balancer_policy_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_balancer_seg_scope', 'balancer_segment_stats', ['city', 'supplier', 'segment_id', 'band_id', 'segment_start'], unique=False)
    op.create_index(op.f('ix_balancer_segment_stats_band_id'), 'balancer_segment_stats', ['band_id'], unique=False)
    op.create_index(op.f('ix_balancer_segment_stats_city'), 'balancer_segment_stats', ['city'], unique=False)
    op.create_index(op.f('ix_balancer_segment_stats_policy_log_id'), 'balancer_segment_stats', ['policy_log_id'], unique=False)
    op.create_index(op.f('ix_balancer_segment_stats_profile_name'), 'balancer_segment_stats', ['profile_name'], unique=False)
    op.create_index(op.f('ix_balancer_segment_stats_segment_id'), 'balancer_segment_stats', ['segment_id'], unique=False)
    op.create_index(op.f('ix_balancer_segment_stats_supplier'), 'balancer_segment_stats', ['supplier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balancer_segment_stats_supplier'), table_name='balancer_segment_stats')
    op.drop_index(op.f('ix_balancer_segment_stats_segment_id'), table_name='balancer_segment_stats')
    op.drop_index(op.f('ix_balancer_segment_stats_profile_name'), table_name='balancer_segment_stats')
    op.drop_index(op.f('ix_balancer_segment_stats_policy_log_id'), table_name='balancer_segment_stats')
    op.drop_index(op.f('ix_balancer_segment_stats_city'), table_name='balancer_segment_stats')
    op.drop_index(op.f('ix_balancer_segment_stats_band_id'), table_name='balancer_segment_stats')
    op.drop_index('ix_balancer_seg_scope', table_name='balancer_segment_stats')
    op.drop_table('balancer_segment_stats')
    op.drop_index(op.f('ix_balancer_order_facts_supplier'), table_name='balancer_order_facts')
    op.drop_index(op.f('ix_balancer_order_facts_segment_id'), table_name='balancer_order_facts')
    op.drop_index('ix_balancer_order_facts_scope', table_name='balancer_order_facts')
    op.drop_index(op.f('ix_balancer_order_facts_profile_name'), table_name='balancer_order_facts')
    op.drop_index(op.f('ix_balancer_order_facts_policy_log_id'), table_name='balancer_order_facts')
    op.drop_index(op.f('ix_balancer_order_facts_order_id'), table_name='balancer_order_facts')
    op.drop_index(op.f('ix_balancer_order_facts_city'), table_name='balancer_order_facts')
    op.drop_index(op.f('ix_balancer_order_facts_band_id'), table_name='balancer_order_facts')
    op.drop_table('balancer_order_facts')
    op.drop_index('ix_balancer_policy_scope', table_name='balancer_policy_log')
    op.drop_index(op.f('ix_balancer_policy_log_supplier'), table_name='balancer_policy_log')
    op.drop_index(op.f('ix_balancer_policy_log_segment_id'), table_name='balancer_policy_log')
    op.drop_index(op.f('ix_balancer_policy_log_hash'), table_name='balancer_policy_log')
    op.drop_index(op.f('ix_balancer_policy_log_city'), table_name='balancer_policy_log')
    op.drop_table('balancer_policy_log')
    # ### end Alembic commands ###
