"""Удалены поля лишние из модели

Revision ID: 0b2f3763beeb
Revises: 9f53948f1a9f
Create Date: 2025-02-07 09:24:27.928486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b2f3763beeb'
down_revision: Union[str, None] = '9f53948f1a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developer_settings', 'error_email_developer')
    op.drop_column('developer_settings', 'google_drive_file_name')
    op.alter_column('enterprise_settings', 'last_stock_upload',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('enterprise_settings', 'last_catalog_upload',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('enterprise_settings', 'email')
    op.drop_column('enterprise_settings', 'file_format')
    op.drop_column('enterprise_settings', 'data_transfer_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise_settings', sa.Column('data_transfer_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('enterprise_settings', sa.Column('file_format', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('enterprise_settings', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('enterprise_settings', 'last_catalog_upload',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('enterprise_settings', 'last_stock_upload',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.add_column('developer_settings', sa.Column('google_drive_file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('developer_settings', sa.Column('error_email_developer', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
