"""balancer: extend live state (best_rules, last_run_key)

Revision ID: 0e54e9d93e75
Revises: 15af0ec9e3c4
Create Date: 2026-01-03 08:39:19.391526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e54e9d93e75'
down_revision: Union[str, None] = '15af0ec9e3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
