"""balancer: extend live state with metrics and freeze

Revision ID: 15af0ec9e3c4
Revises: d5bd7535e448
Create Date: 2026-01-03 08:03:50.614342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15af0ec9e3c4'
down_revision: Union[str, None] = 'd5bd7535e448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balancer_live_state', sa.Column('baseline_metric', sa.Float(), nullable=True))
    op.add_column('balancer_live_state', sa.Column('best_metric', sa.Float(), nullable=True))
    op.add_column('balancer_live_state', sa.Column('best_iter', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('balancer_live_state', sa.Column('last_metric', sa.Float(), nullable=True))
    op.add_column('balancer_live_state', sa.Column('last_segment_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('balancer_live_state', sa.Column('stop_reason', sa.String(), nullable=True))
    op.add_column('balancer_live_state', sa.Column('is_frozen', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balancer_live_state', 'is_frozen')
    op.drop_column('balancer_live_state', 'stop_reason')
    op.drop_column('balancer_live_state', 'last_segment_end')
    op.drop_column('balancer_live_state', 'last_metric')
    op.drop_column('balancer_live_state', 'best_iter')
    op.drop_column('balancer_live_state', 'best_metric')
    op.drop_column('balancer_live_state', 'baseline_metric')
    # ### end Alembic commands ###
