"""Changes Develop Settings

Revision ID: 22360d47b462
Revises: 
Create Date: 2025-03-09 22:02:42.698259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22360d47b462'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developer_settings', 'stock_data_retention')
    op.drop_column('developer_settings', 'catalog_data_retention')
    op.alter_column('mapping_branch', 'id_telegram',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mapping_branch', 'id_telegram',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.add_column('developer_settings', sa.Column('catalog_data_retention', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('developer_settings', sa.Column('stock_data_retention', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
