"""FTP 01

Revision ID: 2569dd83199c
Revises: ed1552a81731
Create Date: 2025-04-25 14:05:59.698342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2569dd83199c'
down_revision: Union[str, None] = 'ed1552a81731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mapping_branch', 'google_folder_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mapping_branch', 'google_folder_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
