"""s

Revision ID: 2fd1127d1aaa
Revises: 627d5a8b58ee
Create Date: 2025-11-01 20:16:31.978600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fd1127d1aaa'
down_revision: Union[str, None] = '627d5a8b58ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_notifications', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.alter_column('client_notifications', 'updated_at', server_default=sa.text('now()'))
    op.execute("UPDATE client_notifications SET updated_at = now() WHERE updated_at IS NULL;")
    op.alter_column('client_notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('competitor_prices', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('competitor_prices', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('dropship_enterprises', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('dropship_enterprises', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    # dropship_enterprises booleans with safe backfill
    op.alter_column('dropship_enterprises', 'is_rrp', server_default=sa.text('false'))
    op.execute("UPDATE dropship_enterprises SET is_rrp = false WHERE is_rrp IS NULL;")
    op.alter_column('dropship_enterprises', 'is_rrp', existing_type=sa.BOOLEAN(), nullable=False)

    op.alter_column('dropship_enterprises', 'is_wholesale', server_default=sa.text('true'))
    op.execute("UPDATE dropship_enterprises SET is_wholesale = true WHERE is_wholesale IS NULL;")
    op.alter_column('dropship_enterprises', 'is_wholesale', existing_type=sa.BOOLEAN(), nullable=False)

    op.alter_column('dropship_enterprises', 'is_active', server_default=sa.text('true'))
    op.execute("UPDATE dropship_enterprises SET is_active = true WHERE is_active IS NULL;")
    op.alter_column('dropship_enterprises', 'is_active', existing_type=sa.BOOLEAN(), nullable=False)

    op.alter_column('dropship_enterprises', 'api_orders_enabled', server_default=sa.text('false'))
    op.execute("UPDATE dropship_enterprises SET api_orders_enabled = false WHERE api_orders_enabled IS NULL;")
    op.alter_column('dropship_enterprises', 'api_orders_enabled', existing_type=sa.BOOLEAN(), nullable=False)

    op.alter_column('dropship_enterprises', 'weekend_work', server_default=sa.text('false'))
    op.execute("UPDATE dropship_enterprises SET weekend_work = false WHERE weekend_work IS NULL;")
    op.alter_column('dropship_enterprises', 'weekend_work', existing_type=sa.BOOLEAN(), nullable=False)

    op.alter_column('dropship_enterprises', 'use_feed_instead_of_gdrive', server_default=sa.text('true'))
    op.execute("UPDATE dropship_enterprises SET use_feed_instead_of_gdrive = true WHERE use_feed_instead_of_gdrive IS NULL;")
    op.alter_column('dropship_enterprises', 'use_feed_instead_of_gdrive', existing_type=sa.BOOLEAN(), nullable=False)

    # priority with server default and backfill
    op.alter_column('dropship_enterprises', 'priority', server_default=sa.text('5'))
    op.execute("UPDATE dropship_enterprises SET priority = 5 WHERE priority IS NULL;")
    op.alter_column('dropship_enterprises', 'priority', existing_type=sa.INTEGER(), nullable=False)
    op.create_index('ix_dropship_enterprises_is_active', 'dropship_enterprises', ['is_active'], unique=False)
    op.create_index('ix_dropship_enterprises_priority', 'dropship_enterprises', ['priority'], unique=False)
    op.add_column('enterprise_settings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('enterprise_settings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    # enterprise_settings booleans with safe backfill (defaults = false)
    op.alter_column('enterprise_settings', 'single_store', server_default=sa.text('false'))
    op.execute("UPDATE enterprise_settings SET single_store = false WHERE single_store IS NULL;")
    op.alter_column('enterprise_settings', 'single_store', existing_type=sa.BOOLEAN(), nullable=False)

    op.alter_column('enterprise_settings', 'order_fetcher', server_default=sa.text('false'))
    op.execute("UPDATE enterprise_settings SET order_fetcher = false WHERE order_fetcher IS NULL;")
    op.alter_column('enterprise_settings', 'order_fetcher', existing_type=sa.BOOLEAN(), nullable=False)

    op.alter_column('enterprise_settings', 'auto_confirm', server_default=sa.text('false'))
    op.execute("UPDATE enterprise_settings SET auto_confirm = false WHERE auto_confirm IS NULL;")
    op.alter_column('enterprise_settings', 'auto_confirm', existing_type=sa.BOOLEAN(), nullable=False)

    op.alter_column('enterprise_settings', 'stock_correction', server_default=sa.text('false'))
    op.execute("UPDATE enterprise_settings SET stock_correction = false WHERE stock_correction IS NULL;")
    op.alter_column('enterprise_settings', 'stock_correction', existing_type=sa.BOOLEAN(), nullable=False)
    op.create_index('ix_enterprise_settings_data_format', 'enterprise_settings', ['data_format'], unique=False)
    op.create_index('ix_enterprise_settings_single_store', 'enterprise_settings', ['single_store'], unique=False)
    op.add_column('inventory_data', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.alter_column('inventory_data', 'updated_at', server_default=sa.text('now()'))
    op.execute("UPDATE inventory_data SET updated_at = now() WHERE updated_at IS NULL;")
    op.alter_column('inventory_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('inventory_stock', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.alter_column('inventory_stock', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('inventory_stock', 'price_reserve',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('inventory_stock', 'updated_at', server_default=sa.text('now()'))
    op.execute("UPDATE inventory_stock SET updated_at = now() WHERE updated_at IS NULL;")
    op.alter_column('inventory_stock', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_inventory_stock_available', 'inventory_stock', ['enterprise_code'], unique=False, postgresql_where=sa.text('qty > 0'))
    op.create_index('ix_inventory_stock_ent_code', 'inventory_stock', ['enterprise_code'], unique=False)
    op.create_index('ix_inventory_stock_ent_code_item', 'inventory_stock', ['enterprise_code', 'code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_stock_ent_code_item', table_name='inventory_stock')
    op.drop_index('ix_inventory_stock_ent_code', table_name='inventory_stock')
    op.drop_index('ix_inventory_stock_available', table_name='inventory_stock', postgresql_where=sa.text('qty > 0'))
    op.alter_column('inventory_stock', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('inventory_stock', 'price_reserve',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('inventory_stock', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('inventory_stock', 'created_at')
    op.alter_column('inventory_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('inventory_data', 'created_at')
    op.drop_index('ix_enterprise_settings_single_store', table_name='enterprise_settings')
    op.drop_index('ix_enterprise_settings_data_format', table_name='enterprise_settings')
    op.alter_column('enterprise_settings', 'stock_correction',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('enterprise_settings', 'auto_confirm',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('enterprise_settings', 'order_fetcher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('enterprise_settings', 'single_store',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('enterprise_settings', 'updated_at')
    op.drop_column('enterprise_settings', 'created_at')
    op.drop_index('ix_dropship_enterprises_priority', table_name='dropship_enterprises')
    op.drop_index('ix_dropship_enterprises_is_active', table_name='dropship_enterprises')
    op.alter_column('dropship_enterprises', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dropship_enterprises', 'use_feed_instead_of_gdrive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dropship_enterprises', 'weekend_work',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dropship_enterprises', 'api_orders_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dropship_enterprises', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dropship_enterprises', 'is_wholesale',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dropship_enterprises', 'is_rrp',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('dropship_enterprises', 'updated_at')
    op.drop_column('dropship_enterprises', 'created_at')
    op.drop_column('competitor_prices', 'updated_at')
    op.drop_column('competitor_prices', 'created_at')
    op.alter_column('client_notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('client_notifications', 'created_at')
    # ### end Alembic commands ###
