"""add balancer_test_state

Revision ID: 359537438c0f
Revises: 0b25e7fbb760
Create Date: 2025-12-26 15:39:34.914520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359537438c0f'
down_revision: Union[str, None] = '0b25e7fbb760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balancer_test_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('supplier', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('band_id', sa.String(), nullable=False),
    sa.Column('day_date', sa.Date(), nullable=False),
    sa.Column('current_porog', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('step', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('min_porog', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('max_porog', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("mode IN ('TEST')", name='ck_balancer_test_state_mode'),
    sa.CheckConstraint('current_porog <= max_porog', name='ck_balancer_test_state_porog_le_max'),
    sa.CheckConstraint('current_porog >= min_porog', name='ck_balancer_test_state_porog_ge_min'),
    sa.CheckConstraint('direction IN (1, -1)', name='ck_balancer_test_state_direction'),
    sa.CheckConstraint('max_porog >= min_porog', name='ck_balancer_test_state_max_ge_min'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_name', 'city', 'supplier', 'segment_id', 'band_id', 'day_date', name='uq_balancer_test_state_key')
    )
    op.create_index(op.f('ix_balancer_test_state_band_id'), 'balancer_test_state', ['band_id'], unique=False)
    op.create_index(op.f('ix_balancer_test_state_city'), 'balancer_test_state', ['city'], unique=False)
    op.create_index(op.f('ix_balancer_test_state_day_date'), 'balancer_test_state', ['day_date'], unique=False)
    op.create_index(op.f('ix_balancer_test_state_profile_name'), 'balancer_test_state', ['profile_name'], unique=False)
    op.create_index('ix_balancer_test_state_scope', 'balancer_test_state', ['city', 'supplier', 'segment_id', 'band_id', 'day_date'], unique=False)
    op.create_index(op.f('ix_balancer_test_state_segment_id'), 'balancer_test_state', ['segment_id'], unique=False)
    op.create_index(op.f('ix_balancer_test_state_supplier'), 'balancer_test_state', ['supplier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balancer_test_state_supplier'), table_name='balancer_test_state')
    op.drop_index(op.f('ix_balancer_test_state_segment_id'), table_name='balancer_test_state')
    op.drop_index('ix_balancer_test_state_scope', table_name='balancer_test_state')
    op.drop_index(op.f('ix_balancer_test_state_profile_name'), table_name='balancer_test_state')
    op.drop_index(op.f('ix_balancer_test_state_day_date'), table_name='balancer_test_state')
    op.drop_index(op.f('ix_balancer_test_state_city'), table_name='balancer_test_state')
    op.drop_index(op.f('ix_balancer_test_state_band_id'), table_name='balancer_test_state')
    op.drop_table('balancer_test_state')
    # ### end Alembic commands ###
