"""Пересоздание всех миграций

Revision ID: 409a451f2a4c
Revises: 
Create Date: 2025-02-23 12:13:47.903556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409a451f2a4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_branch',
    sa.Column('enterprise_code', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('branch')
    )
    op.drop_column('inventory_data', 'branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_data', sa.Column('branch_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('mapping_branch')
    # ### end Alembic commands ###
