"""As

Revision ID: 48ad86e15311
Revises: 99f5637e087e
Create Date: 2025-11-01 19:07:32.206442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48ad86e15311'
down_revision: Union[str, None] = '99f5637e087e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_notifications', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('client_notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('dropship_enterprises', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('dropship_enterprises', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('dropship_enterprises', 'is_rrp',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dropship_enterprises', 'is_wholesale',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dropship_enterprises', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dropship_enterprises', 'api_orders_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dropship_enterprises', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dropship_enterprises', 'weekend_work',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dropship_enterprises', 'use_feed_instead_of_gdrive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('ix_dropship_enterprises_is_active', 'dropship_enterprises', ['is_active'], unique=False)
    op.create_index('ix_dropship_enterprises_priority', 'dropship_enterprises', ['priority'], unique=False)
    op.add_column('enterprise_settings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('enterprise_settings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('enterprise_settings', 'single_store',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('enterprise_settings', 'order_fetcher',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('enterprise_settings', 'auto_confirm',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('enterprise_settings', 'stock_correction',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('ix_enterprise_settings_data_format', 'enterprise_settings', ['data_format'], unique=False)
    op.create_index('ix_enterprise_settings_single_store', 'enterprise_settings', ['single_store'], unique=False)
    op.add_column('inventory_data', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('inventory_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('inventory_stock', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('inventory_stock', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('inventory_stock', 'price_reserve',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('inventory_stock', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_inventory_stock_available', 'inventory_stock', ['enterprise_code'], unique=False, postgresql_where=sa.text('qty > 0'))
    op.create_index('ix_inventory_stock_ent_code', 'inventory_stock', ['enterprise_code'], unique=False)
    op.create_index('ix_inventory_stock_ent_code_item', 'inventory_stock', ['enterprise_code', 'code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_stock_ent_code_item', table_name='inventory_stock')
    op.drop_index('ix_inventory_stock_ent_code', table_name='inventory_stock')
    op.drop_index('ix_inventory_stock_available', table_name='inventory_stock', postgresql_where=sa.text('qty > 0'))
    op.alter_column('inventory_stock', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('inventory_stock', 'price_reserve',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('inventory_stock', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('inventory_stock', 'created_at')
    op.alter_column('inventory_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('inventory_data', 'created_at')
    op.drop_index('ix_enterprise_settings_single_store', table_name='enterprise_settings')
    op.drop_index('ix_enterprise_settings_data_format', table_name='enterprise_settings')
    op.alter_column('enterprise_settings', 'stock_correction',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('enterprise_settings', 'auto_confirm',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('enterprise_settings', 'order_fetcher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('enterprise_settings', 'single_store',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('enterprise_settings', 'updated_at')
    op.drop_column('enterprise_settings', 'created_at')
    op.drop_index('ix_dropship_enterprises_priority', table_name='dropship_enterprises')
    op.drop_index('ix_dropship_enterprises_is_active', table_name='dropship_enterprises')
    op.alter_column('dropship_enterprises', 'use_feed_instead_of_gdrive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dropship_enterprises', 'weekend_work',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dropship_enterprises', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dropship_enterprises', 'api_orders_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dropship_enterprises', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dropship_enterprises', 'is_wholesale',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dropship_enterprises', 'is_rrp',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('dropship_enterprises', 'updated_at')
    op.drop_column('dropship_enterprises', 'created_at')
    op.alter_column('client_notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('client_notifications', 'created_at')
    # ### end Alembic commands ###
