"""2010

Revision ID: 51dc89364365
Revises: 2d44a8befc2a
Create Date: 2025-10-21 16:18:43.490378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51dc89364365'
down_revision: Union[str, None] = '2d44a8befc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_prices',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('competitor_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('code', 'city')
    )
    op.create_index('ix_competitor_prices_city', 'competitor_prices', ['city'], unique=False)
    op.create_index(op.f('ix_competitor_prices_code'), 'competitor_prices', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_prices_code'), table_name='competitor_prices')
    op.drop_index('ix_competitor_prices_city', table_name='competitor_prices')
    op.drop_table('competitor_prices')
    # ### end Alembic commands ###
