"""Add extra supplier slots and wholesale price

Revision ID: 593d49338f2d
Revises: 0b00fe471b2f
Create Date: 2025-11-30 12:12:11.475993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593d49338f2d'
down_revision: Union[str, None] = '0b00fe471b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_mapping', sa.Column('Name_D11', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Name_D12', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Name_D13', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Name_D14', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Name_D15', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Name_D16', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Name_D17', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Name_D18', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Name_D19', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Name_D20', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Code_D11', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Code_D12', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Code_D13', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Code_D14', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Code_D15', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Code_D16', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Code_D17', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Code_D18', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Code_D19', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('catalog_mapping', sa.Column('Code_D20', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('offers', sa.Column('wholesale_price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'wholesale_price')
    op.drop_column('catalog_mapping', 'Code_D20')
    op.drop_column('catalog_mapping', 'Code_D19')
    op.drop_column('catalog_mapping', 'Code_D18')
    op.drop_column('catalog_mapping', 'Code_D17')
    op.drop_column('catalog_mapping', 'Code_D16')
    op.drop_column('catalog_mapping', 'Code_D15')
    op.drop_column('catalog_mapping', 'Code_D14')
    op.drop_column('catalog_mapping', 'Code_D13')
    op.drop_column('catalog_mapping', 'Code_D12')
    op.drop_column('catalog_mapping', 'Code_D11')
    op.drop_column('catalog_mapping', 'Name_D20')
    op.drop_column('catalog_mapping', 'Name_D19')
    op.drop_column('catalog_mapping', 'Name_D18')
    op.drop_column('catalog_mapping', 'Name_D17')
    op.drop_column('catalog_mapping', 'Name_D16')
    op.drop_column('catalog_mapping', 'Name_D15')
    op.drop_column('catalog_mapping', 'Name_D14')
    op.drop_column('catalog_mapping', 'Name_D13')
    op.drop_column('catalog_mapping', 'Name_D12')
    op.drop_column('catalog_mapping', 'Name_D11')
    # ### end Alembic commands ###
