"""2gs

Revision ID: 59cf57f3ffbb
Revises: 8a2b0c47642c
Create Date: 2025-10-19 14:49:02.827237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59cf57f3ffbb'
down_revision: Union[str, None] = '8a2b0c47642c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_mapping',
    sa.Column('ID', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Producer', sa.String(), nullable=True),
    sa.Column('Barcode', sa.String(), nullable=True),
    sa.Column('Guid', sa.String(), nullable=True),
    sa.Column('Code_Tabletki', sa.String(), nullable=True),
    sa.Column('Name_D1', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Name_D2', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Name_D3', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Name_D4', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Name_D5', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Name_D6', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Name_D7', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Name_D8', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Name_D9', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Name_D10', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Code_D1', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Code_D2', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Code_D3', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Code_D4', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Code_D5', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Code_D6', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Code_D7', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Code_D8', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Code_D9', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('Code_D10', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_mapping')
    # ### end Alembic commands ###
