"""Initial migrations

Revision ID: 5bf89a02fa8c
Revises: 
Create Date: 2024-12-06 10:00:43.752753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf89a02fa8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_notifications',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enterprise_code', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('format_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('format_name')
    )
    op.create_index(op.f('ix_data_formats_id'), 'data_formats', ['id'], unique=False)
    op.create_table('developer_settings',
    sa.Column('developer_login', sa.String(), nullable=False),
    sa.Column('developer_password', sa.String(), nullable=False),
    sa.Column('endpoint_catalog', sa.String(), nullable=True),
    sa.Column('endpoint_stock', sa.String(), nullable=True),
    sa.Column('endpoint_orders', sa.String(), nullable=True),
    sa.Column('telegram_token_developer', sa.String(), nullable=True),
    sa.Column('error_email_developer', sa.String(), nullable=True),
    sa.Column('google_drive_file_name', sa.String(), nullable=True),
    sa.Column('catalog_data_retention', sa.Integer(), nullable=True),
    sa.Column('stock_data_retention', sa.Integer(), nullable=True),
    sa.Column('morion', sa.String(), nullable=True),
    sa.Column('tabletki', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('optima', sa.String(), nullable=True),
    sa.Column('badm', sa.String(), nullable=True),
    sa.Column('venta', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('developer_login')
    )
    op.create_table('enterprise_settings',
    sa.Column('enterprise_code', sa.String(), nullable=False),
    sa.Column('enterprise_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('enterprise_login', sa.String(), nullable=True),
    sa.Column('enterprise_password', sa.String(), nullable=True),
    sa.Column('tabletki_login', sa.String(), nullable=True),
    sa.Column('tabletki_password', sa.String(), nullable=True),
    sa.Column('stock_upload_frequency', sa.Integer(), nullable=True),
    sa.Column('catalog_upload_frequency', sa.Integer(), nullable=True),
    sa.Column('data_transfer_method', sa.String(), nullable=True),
    sa.Column('google_drive_folder_id_ref', sa.String(), nullable=True),
    sa.Column('google_drive_folder_id_rest', sa.String(), nullable=True),
    sa.Column('file_format', sa.String(), nullable=True),
    sa.Column('data_format', sa.String(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('single_store', sa.Boolean(), nullable=True),
    sa.Column('store_serial', sa.String(), nullable=True),
    sa.Column('last_stock_upload', sa.DateTime(), nullable=True),
    sa.Column('last_catalog_upload', sa.DateTime(), nullable=True),
    sa.Column('stock_correction', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('enterprise_code')
    )
    op.create_table('inventory_data',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('producer', sa.String(), nullable=False),
    sa.Column('vat', sa.Float(), nullable=False),
    sa.Column('morion', sa.String(), nullable=True),
    sa.Column('tabletki', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('optima', sa.String(), nullable=True),
    sa.Column('badm', sa.String(), nullable=True),
    sa.Column('venta', sa.String(), nullable=True),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('inventory_stock',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price_reserve', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('branch', 'code')
    )
    op.create_table('reserved_items',
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('branch', 'code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserved_items')
    op.drop_table('inventory_stock')
    op.drop_table('inventory_data')
    op.drop_table('enterprise_settings')
    op.drop_table('developer_settings')
    op.drop_index(op.f('ix_data_formats_id'), table_name='data_formats')
    op.drop_table('data_formats')
    op.drop_table('client_notifications')
    # ### end Alembic commands ###
