"""01

Revision ID: 5cd09580eb9e
Revises: 2569dd83199c
Create Date: 2025-10-18 16:01:38.841870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd09580eb9e'
down_revision: Union[str, None] = '2569dd83199c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Catalog_mapping',
    sa.Column('ID', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Producer', sa.String(), nullable=False),
    sa.Column('Barcode', sa.String(), nullable=False),
    sa.Column('Guid', sa.String(), nullable=False),
    sa.Column('Code_Tabletki', sa.String(), nullable=False),
    sa.Column('Name_D1', sa.String(), nullable=False),
    sa.Column('Name_D2', sa.String(), nullable=False),
    sa.Column('Name_D3', sa.String(), nullable=False),
    sa.Column('Name_D4', sa.String(), nullable=False),
    sa.Column('Name_D5', sa.String(), nullable=False),
    sa.Column('Name_D6', sa.String(), nullable=False),
    sa.Column('Name_D7', sa.String(), nullable=False),
    sa.Column('Name_D8', sa.String(), nullable=False),
    sa.Column('Name_D9', sa.String(), nullable=False),
    sa.Column('Name_D10', sa.String(), nullable=False),
    sa.Column('Code_D1', sa.String(), nullable=False),
    sa.Column('Code_D2', sa.String(), nullable=False),
    sa.Column('Code_D3', sa.String(), nullable=False),
    sa.Column('Code_D4', sa.String(), nullable=False),
    sa.Column('Code_D5', sa.String(), nullable=False),
    sa.Column('Code_D6', sa.String(), nullable=False),
    sa.Column('Code_D7', sa.String(), nullable=False),
    sa.Column('Code_D8', sa.String(), nullable=False),
    sa.Column('Code_D9', sa.String(), nullable=False),
    sa.Column('Code_D10', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Catalog_mapping')
    # ### end Alembic commands ###
