"""05

Revision ID: 66228589f180
Revises: a671a1730285
Create Date: 2025-10-18 16:36:31.950414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66228589f180'
down_revision: Union[str, None] = 'a671a1730285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalog_mapping', 'Name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Producer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Barcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Guid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Code_Tabletki',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Name_D1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Name_D2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Name_D3',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Name_D4',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Name_D5',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Name_D6',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Name_D7',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Name_D8',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Name_D9',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Name_D10',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Code_D1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Code_D2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Code_D3',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Code_D4',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Code_D5',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Code_D6',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Code_D7',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Code_D8',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Code_D9',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalog_mapping', 'Code_D10',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalog_mapping', 'Code_D10',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Code_D9',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Code_D8',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Code_D7',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Code_D6',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Code_D5',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Code_D4',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Code_D3',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Code_D2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Code_D1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Name_D10',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Name_D9',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Name_D8',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Name_D7',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Name_D6',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Name_D5',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Name_D4',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Name_D3',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Name_D2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Name_D1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Code_Tabletki',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Guid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Barcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Producer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalog_mapping', 'Name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
