"""Recreate missing migration

Revision ID: 72f5f5261c7e
Revises: cedd7990c00a
Create Date: 2025-03-16 07:07:16.962731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f5f5261c7e'
down_revision: Union[str, None] = 'cedd7990c00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_settings', sa.Column('message_orders', sa.Boolean(), nullable=True))
    op.drop_column('developer_settings', 'stock_data_retention')
    op.drop_column('developer_settings', 'catalog_data_retention')
    op.add_column('mapping_branch', sa.Column('id_telegram', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_branch', 'id_telegram')
    op.add_column('developer_settings', sa.Column('catalog_data_retention', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('developer_settings', sa.Column('stock_data_retention', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('developer_settings', 'message_orders')
    # ### end Alembic commands ###
