"""11

Revision ID: 7749fc230754
Revises: a6475ec45db4
Create Date: 2025-10-21 21:11:54.300243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7749fc230754'
down_revision: Union[str, None] = 'a6475ec45db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_mapping', sa.Column('id', sa.String(), nullable=False))
    op.drop_column('catalog_mapping', 'ID')
    op.add_column('competitor_prices', sa.Column('product_code', sa.String(), nullable=False))
    op.drop_index('ix_competitor_prices_code', table_name='competitor_prices')
    op.create_index(op.f('ix_competitor_prices_product_code'), 'competitor_prices', ['product_code'], unique=False)
    op.drop_column('competitor_prices', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_prices', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_competitor_prices_product_code'), table_name='competitor_prices')
    op.create_index('ix_competitor_prices_code', 'competitor_prices', ['code'], unique=False)
    op.drop_column('competitor_prices', 'product_code')
    op.add_column('catalog_mapping', sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('catalog_mapping', 'id')
    # ### end Alembic commands ###
