"""Add auto_confirm column

Revision ID: 8a30f8954e26
Revises: 97e3c532bd4f
Create Date: 2025-03-07 07:34:09.685713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a30f8954e26'
down_revision: Union[str, None] = '97e3c532bd4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise_settings', sa.Column('auto_confirm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enterprise_settings', 'auto_confirm')
    # ### end Alembic commands ###
