"""Remove email from enterprise_settings

Revision ID: a429abdadc33
Revises: 0b2f3763beeb
Create Date: 2025-02-13 14:32:35.848493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a429abdadc33'
down_revision: Union[str, None] = '0b2f3763beeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enterprise_settings', 'enterprise_login')
    op.drop_column('enterprise_settings', 'enterprise_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise_settings', sa.Column('enterprise_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('enterprise_settings', sa.Column('enterprise_login', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
