"""04

Revision ID: a671a1730285
Revises: c3157eebce79
Create Date: 2025-10-18 16:04:48.689804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a671a1730285'
down_revision: Union[str, None] = 'c3157eebce79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_mapping',
    sa.Column('ID', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Producer', sa.String(), nullable=False),
    sa.Column('Barcode', sa.String(), nullable=False),
    sa.Column('Guid', sa.String(), nullable=False),
    sa.Column('Code_Tabletki', sa.String(), nullable=False),
    sa.Column('Name_D1', sa.String(), nullable=False),
    sa.Column('Name_D2', sa.String(), nullable=False),
    sa.Column('Name_D3', sa.String(), nullable=False),
    sa.Column('Name_D4', sa.String(), nullable=False),
    sa.Column('Name_D5', sa.String(), nullable=False),
    sa.Column('Name_D6', sa.String(), nullable=False),
    sa.Column('Name_D7', sa.String(), nullable=False),
    sa.Column('Name_D8', sa.String(), nullable=False),
    sa.Column('Name_D9', sa.String(), nullable=False),
    sa.Column('Name_D10', sa.String(), nullable=False),
    sa.Column('Code_D1', sa.String(), nullable=False),
    sa.Column('Code_D2', sa.String(), nullable=False),
    sa.Column('Code_D3', sa.String(), nullable=False),
    sa.Column('Code_D4', sa.String(), nullable=False),
    sa.Column('Code_D5', sa.String(), nullable=False),
    sa.Column('Code_D6', sa.String(), nullable=False),
    sa.Column('Code_D7', sa.String(), nullable=False),
    sa.Column('Code_D8', sa.String(), nullable=False),
    sa.Column('Code_D9', sa.String(), nullable=False),
    sa.Column('Code_D10', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('сatalog_mapping')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('сatalog_mapping',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Producer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Barcode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Guid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Code_Tabletki', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name_D1', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name_D2', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name_D3', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name_D4', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name_D5', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name_D6', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name_D7', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name_D8', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name_D9', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name_D10', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Code_D1', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Code_D2', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Code_D3', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Code_D4', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Code_D5', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Code_D6', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Code_D7', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Code_D8', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Code_D9', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Code_D10', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name='сatalog_mapping_pkey')
    )
    op.drop_table('catalog_mapping')
    # ### end Alembic commands ###
