"""07

Revision ID: b2185162aa32
Revises: 2d44a8befc2a
Create Date: 2025-10-20 15:44:51.563110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2185162aa32'
down_revision: Union[str, None] = '2d44a8befc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dropship_enterprises',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('feed_url', sa.String(), nullable=True),
    sa.Column('gdrive_folder', sa.String(), nullable=True),
    sa.Column('is_rrp', sa.Boolean(), nullable=True),
    sa.Column('is_wholesale', sa.Boolean(), nullable=True),
    sa.Column('profit_percent', sa.Float(), nullable=True),
    sa.Column('retail_markup', sa.Float(), nullable=True),
    sa.Column('min_markup_threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('api_orders_enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('weekend_work', sa.Boolean(), nullable=True),
    sa.Column('use_feed_instead_of_gdrive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_dropship_enterprises_code'), 'dropship_enterprises', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dropship_enterprises_code'), table_name='dropship_enterprises')
    op.drop_table('dropship_enterprises')
    # ### end Alembic commands ###
