"""Создана база данных для мапинга кодов магазина

Revision ID: b686a2966958
Revises: c29008d347c8
Create Date: 2025-02-22 13:01:23.847325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b686a2966958'
down_revision: Union[str, None] = 'c29008d347c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_branch', sa.Column('branch', sa.String(), nullable=False))
    op.add_column('mapping_branch', sa.Column('store_id', sa.String(), nullable=False))
    op.drop_column('mapping_branch', 'google_drive_folder_id_rest')
    op.drop_column('mapping_branch', 'tabletki_password')
    op.drop_column('mapping_branch', 'branch_id')
    op.drop_column('mapping_branch', 'tabletki_login')
    op.drop_column('mapping_branch', 'last_stock_upload')
    op.drop_column('mapping_branch', 'data_format')
    op.drop_column('mapping_branch', 'stock_upload_frequency')
    op.drop_column('mapping_branch', 'enterprise_name')
    op.drop_column('mapping_branch', 'store_serial')
    op.drop_column('mapping_branch', 'discount_rate')
    op.drop_column('mapping_branch', 'single_store')
    op.drop_column('mapping_branch', 'token')
    op.drop_column('mapping_branch', 'catalog_upload_frequency')
    op.drop_column('mapping_branch', 'last_catalog_upload')
    op.drop_column('mapping_branch', 'stock_correction')
    op.drop_column('mapping_branch', 'google_drive_folder_id_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_branch', sa.Column('google_drive_folder_id_ref', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('stock_correction', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('last_catalog_upload', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('catalog_upload_frequency', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('single_store', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('discount_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('store_serial', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('enterprise_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mapping_branch', sa.Column('stock_upload_frequency', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('data_format', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('last_stock_upload', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('tabletki_login', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('branch_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mapping_branch', sa.Column('tabletki_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mapping_branch', sa.Column('google_drive_folder_id_rest', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mapping_branch', 'store_id')
    op.drop_column('mapping_branch', 'branch')
    # ### end Alembic commands ###
