"""Test 3

Revision ID: b76062b9a310
Revises: 78af81e42b46
Create Date: 2025-03-07 12:04:38.634921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76062b9a310'
down_revision: Union[str, None] = '78af81e42b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_data', sa.Column('enterprise_code', sa.String(), nullable=False))
    op.create_foreign_key(None, 'inventory_data', 'enterprise_settings', ['enterprise_code'], ['enterprise_code'])
    op.add_column('inventory_stock', sa.Column('enterprise_code', sa.String(), nullable=False))
    op.create_foreign_key(None, 'inventory_stock', 'enterprise_settings', ['enterprise_code'], ['enterprise_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_stock', type_='foreignkey')
    op.drop_column('inventory_stock', 'enterprise_code')
    op.drop_constraint(None, 'inventory_data', type_='foreignkey')
    op.drop_column('inventory_data', 'enterprise_code')
    # ### end Alembic commands ###
