"""Added token column to enterprise_settings

Revision ID: c29008d347c8
Revises: a429abdadc33
Create Date: 2025-02-22 12:36:16.299427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29008d347c8'
down_revision: Union[str, None] = 'a429abdadc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_data', 'branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_data', sa.Column('branch_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
