"""A

Revision ID: c846e7ac972c
Revises: cae1320e8108
Create Date: 2025-04-24 13:39:10.151503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c846e7ac972c'
down_revision: Union[str, None] = 'cae1320e8108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_branch', sa.Column('google_folder_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_branch', 'google_folder_id')
    # ### end Alembic commands ###
