"""папка гугл в маппинг бренчs

Revision ID: cae1320e8108
Revises: f4543522684c
Create Date: 2025-04-24 13:31:40.649236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae1320e8108'
down_revision: Union[str, None] = 'f4543522684c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Шаг 1: добавить колонку с nullable=True
    op.add_column('mapping_branch', sa.Column('google_folder_id', sa.String(), nullable=True))

    # Шаг 2: временно обновить все строки, чтобы избежать null
    op.execute("UPDATE mapping_branch SET google_folder_id = '' WHERE google_folder_id IS NULL")

    # Шаг 3: установить ограничение NOT NULL
    op.alter_column('mapping_branch', 'google_folder_id', nullable=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_branch', 'google_folder_id')
    # ### end Alembic commands ###
