"""08

Revision ID: cd08a9e6601e
Revises: a0f60eea3d8a
Create Date: 2025-10-21 20:24:02.559945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd08a9e6601e'
down_revision: Union[str, None] = 'a0f60eea3d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('supplier_code', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code', 'supplier_code', 'city', name='uq_offers_product_supplier_city')
    )
    op.create_index(op.f('ix_offers_city'), 'offers', ['city'], unique=False)
    op.create_index('ix_offers_city_product_price', 'offers', ['city', 'product_code', 'price'], unique=False)
    op.create_index('ix_offers_city_stock_pos', 'offers', ['city'], unique=False, postgresql_where=sa.text('stock > 0'))
    op.create_index(op.f('ix_offers_product_code'), 'offers', ['product_code'], unique=False)
    op.create_index(op.f('ix_offers_supplier_code'), 'offers', ['supplier_code'], unique=False)
    op.add_column('dropship_enterprises', sa.Column('city', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dropship_enterprises', 'city')
    op.drop_index(op.f('ix_offers_supplier_code'), table_name='offers')
    op.drop_index(op.f('ix_offers_product_code'), table_name='offers')
    op.drop_index('ix_offers_city_stock_pos', table_name='offers', postgresql_where=sa.text('stock > 0'))
    op.drop_index('ix_offers_city_product_price', table_name='offers')
    op.drop_index(op.f('ix_offers_city'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
