"""New telegram

Revision ID: cedd7990c00a
Revises: 22360d47b462
Create Date: 2025-03-15 16:29:43.060520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedd7990c00a'
down_revision: Union[str, None] = '22360d47b462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_settings', sa.Column('message_orders', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developer_settings', 'message_orders')
    # ### end Alembic commands ###
