"""Telegram 3

Revision ID: d150ae214f9e
Revises: a8a69dc301fd
Create Date: 2025-03-08 21:13:16.338945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd150ae214f9e'
down_revision: Union[str, None] = 'a8a69dc301fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_branch', sa.Column('ID_telegram', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_branch', 'ID_telegram')
    # ### end Alembic commands ###
