"""balancer: add live state table

Revision ID: d5bd7535e448
Revises: 359537438c0f
Create Date: 2026-01-02 16:11:57.847807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5bd7535e448'
down_revision: Union[str, None] = '359537438c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balancer_live_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('supplier', sa.String(), nullable=False),
    sa.Column('day_date', sa.Date(), nullable=False),
    sa.Column('live_iter', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('day_orders_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_policy_log_id', sa.BigInteger(), nullable=True),
    sa.Column('is_limit_reached', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("mode IN ('LIVE')", name='ck_balancer_live_state_mode'),
    sa.ForeignKeyConstraint(['last_policy_log_id'], ['balancer_policy_log.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mode', 'supplier', 'day_date', name='uq_balancer_live_state_key')
    )
    op.create_index(op.f('ix_balancer_live_state_day_date'), 'balancer_live_state', ['day_date'], unique=False)
    op.create_index(op.f('ix_balancer_live_state_last_policy_log_id'), 'balancer_live_state', ['last_policy_log_id'], unique=False)
    op.create_index('ix_balancer_live_state_scope', 'balancer_live_state', ['supplier', 'day_date'], unique=False)
    op.create_index(op.f('ix_balancer_live_state_supplier'), 'balancer_live_state', ['supplier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balancer_live_state_supplier'), table_name='balancer_live_state')
    op.drop_index('ix_balancer_live_state_scope', table_name='balancer_live_state')
    op.drop_index(op.f('ix_balancer_live_state_last_policy_log_id'), table_name='balancer_live_state')
    op.drop_index(op.f('ix_balancer_live_state_day_date'), table_name='balancer_live_state')
    op.drop_table('balancer_live_state')
    # ### end Alembic commands ###
