"""Telegram 1

Revision ID: ececdc85fc1e
Revises: b76062b9a310
Create Date: 2025-03-08 20:03:27.924268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ececdc85fc1e'
down_revision: Union[str, None] = 'b76062b9a310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_branch', sa.Column('ID_telegram', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_branch', 'ID_telegram')
    # ### end Alembic commands ###
