"""order_fetche.

Revision ID: f31ba5745486
Revises: 72f5f5261c7e
Create Date: 2025-04-02 09:06:54.189712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31ba5745486'
down_revision: Union[str, None] = '72f5f5261c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise_settings', sa.Column('order_fetcher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enterprise_settings', 'order_fetcher')
    # ### end Alembic commands ###
