"""Test 06.04

Revision ID: f4543522684c
Revises: f31ba5745486
Create Date: 2025-04-06 15:45:20.732022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4543522684c'
down_revision: Union[str, None] = 'f31ba5745486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise_settings', sa.Column('order_fetcher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enterprise_settings', 'order_fetcher')
    # ### end Alembic commands ###
